name: CI Pipeline for Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Step 1: Setup JDK 11 (puedes cambiar a la versión que usas) –nombre del paso lo puedo cambiar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 
        uses: actions/setup-java@v2
        with:
          java-version: '23' 
          distribution: 'adoptopenjdk'

      - name: Install dependencies (Maven)
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build project using Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/test-classes #validar que este esta carpeta dentro del proyecto

  # Optional: Upload logs or other artifacts
  #upload-artifacts:
   # runs-on: ubuntu-latest
    #needs: build
    #steps:
     # - name: Upload logs or other artifacts
      #  uses: actions/upload-artifact@v2
       # with:
        #  name: selenium-logs
         # path: /path/to/your/logs
