name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Cambiar de ubuntu-latest a windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven  # Acelera las compilaciones futuras

      - name: Build project using Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test

      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/test-classes

  # #Optional: Upload logs or other artifacts.
  #upload-artifacts:
   # runs-on: windows-latest  # Cambiar a windows-latest si decides usar esta sección
    #needs: build
    #steps:
     # - name: Upload logs or other artifacts
      #  uses: actions/upload-artifact@v2
       # with:
        #  name: selenium-logs
         # path: /path/to/your/logs